# Generated by Django 4.1.7 on 2023-02-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_asignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.TextField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.TextField(max_length=150)),
                ('password', models.TextField(max_length=150)),
                ('fecha_de_creacion', models.CharField(max_length=50)),
                ('estados', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='actividaporRealizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150)),
                ('fecha_vencimiento', models.DateField()),
                ('prioridad', models.TextField(max_length=150)),
                ('estado', models.TextField(max_length=150)),
                ('fecha_creacion', models.DateField()),
                ('usuario_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_de_Comentario', to='core.usuario_asignado')),
            ],
        ),
    ]
