# Generated by Django 4.1.7 on 2023-02-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaporrealizar',
            name='usuario_asig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usario_asignado', to='core.usuario_asignado'),
        ),
        migrations.AlterField(
            model_name='usuario_asignado',
            name='fecha_de_creacion',
            field=models.DateField(),
        ),
    ]
