# Generated by Django 4.1.7 on 2023-02-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_actividaporrealizar_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_asignado',
            name='estados',
            field=models.TextField(default=True),
        ),
    ]
